import NavBar from './components/navBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ExpressWay Logistics',
  description: 'Generated by Kev y Jose',
}

type Time = {
  datetime: string;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}><NavBar/>{children}</body>
    </html>
  )
}
